# Generated by Django 4.1.3 on 2022-11-14 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='candies', to='shop.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='candy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='candy',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=16, verbose_name='phone_number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('comment', models.CharField(max_length=255, verbose_name='comment')),
                ('is_complited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='orders',
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('candy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='candy_items', to='shop.candy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='candy_items', to='shop.order')),
            ],
        ),
    ]
