# Generated by Django 4.1.3 on 2022-11-18 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_candy_category_alter_candy_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_complited',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='delivery_time'),
        ),
        migrations.AlterField(
            model_name='candyitem',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0,
                max_digits=10, verbose_name='price'
            ),
        ),
    ]
